professortitles-- MySQL Script generated by MySQL Workbench
-- 02/13/15 10:40:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema universitydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universitydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `universitydb` ;

-- -----------------------------------------------------
-- Table `universitydb`.`faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universitydb`.`faculties` (
  `FacultiesID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`FacultiesID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `universitydb`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universitydb`.`departments` (
  `DepartmentID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `FacultyID` INT(11) NOT NULL,
  `faculties_FacultiesID` INT(11) NOT NULL,
  PRIMARY KEY (`DepartmentID`),
  INDEX `fk_departments_faculties1_idx` (`faculties_FacultiesID` ASC),
  CONSTRAINT `fk_departments_faculties1`
    FOREIGN KEY (`faculties_FacultiesID`)
    REFERENCES `universitydb`.`faculties` (`FacultiesID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `universitydb`.`professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universitydb`.`professors` (
  `IDProfessors` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `TitleID` INT(11) NOT NULL,
  `DepartmentID` INT(11) NOT NULL,
  `departments_DepartmentID` INT(11) NOT NULL,
  PRIMARY KEY (`IDProfessors`),
  INDEX `fk_professors_departments1_idx` (`departments_DepartmentID` ASC),
  CONSTRAINT `fk_professors_departments1`
    FOREIGN KEY (`departments_DepartmentID`)
    REFERENCES `universitydb`.`departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `universitydb`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universitydb`.`courses` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `DeparmentID` INT(11) NOT NULL,
  `ProfessorID` INT(11) NOT NULL,
  `professors_IDProfessors` INT(11) NOT NULL,
  `departments_DepartmentID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_courses_professors1_idx` (`professors_IDProfessors` ASC),
  INDEX `fk_courses_departments1_idx` (`departments_DepartmentID` ASC),
  CONSTRAINT `fk_courses_professors1`
    FOREIGN KEY (`professors_IDProfessors`)
    REFERENCES `universitydb`.`professors` (`IDProfessors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_departments1`
    FOREIGN KEY (`departments_DepartmentID`)
    REFERENCES `universitydb`.`departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `universitydb`.`professortitles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universitydb`.`professortitles` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `professors_IDProfessors` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_professortitles_professors_idx` (`professors_IDProfessors` ASC),
  CONSTRAINT `fk_professortitles_professors`
    FOREIGN KEY (`professors_IDProfessors`)
    REFERENCES `universitydb`.`professors` (`IDProfessors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `universitydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universitydb`.`students` (
  `StudentID` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `LastName` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `CourseID` INT(11) NOT NULL,
  `FacultyID` INT(11) NOT NULL,
  `courses_ID` INT(11) NOT NULL,
  `faculties_FacultiesID` INT(11) NOT NULL,
  PRIMARY KEY (`StudentID`),
  INDEX `fk_students_courses1_idx` (`courses_ID` ASC),
  INDEX `fk_students_faculties1_idx` (`faculties_FacultiesID` ASC),
  CONSTRAINT `fk_students_courses1`
    FOREIGN KEY (`courses_ID`)
    REFERENCES `universitydb`.`courses` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_faculties1`
    FOREIGN KEY (`faculties_FacultiesID`)
    REFERENCES `universitydb`.`faculties` (`FacultiesID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
