//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHour
    {
        public WorkHour()
        {
            this.WorkHoursLogs = new HashSet<WorkHoursLog>();
        }
    
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Task { get; set; }
        public Nullable<int> WorkHours { get; set; }
        public string Comment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<WorkHoursLog> WorkHoursLogs { get; set; }
    }
}
