//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLog
    {
        public int ID { get; set; }
        public string OldRecord { get; set; }
        public string NewRecord { get; set; }
        public string Command { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual WorkHour WorkHour { get; set; }
    }
}
