//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeographyMappingsDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.Countries = new HashSet<Country>();
        }
    
        public string CurrencyCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Country> Countries { get; set; }
    }
}
